apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.kafkaPort }}
      protocol: TCP
      name: kafka
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
