apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092
          # https://stackoverflow.com/a/54963334/11438506
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://$(POD_NAME).{{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local:9092
          - name: KAFKA_CREATE_TOPICS
            value: "test:1:1"
          # https://github.com/wurstmeister/kafka-docker/issues/122
          - name: KAFKA_PORT
            value: "9092"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: {{ .Values.service.kafkaPort }}
            name: kafka
