# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: zookeeper
  tag: 3.5
  pullPolicy: Always

service:
  type: ClusterIP
  clientPort: 2181

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
