# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wurstmeister/kafka
  tag: 2.12-2.2.0
  pullPolicy: Always

service:
  type: ClusterIP
  kafkaPort: 9092

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
